components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
        hobby:
          enum:
            - Camping
            - Winter Sports